### ISSUE TITLE
Adding Prefix or Suffix to Classes and Tables Names

### ISSUE THREAD

**Issue by antoineviscardi** [agronholm/sqlacodegen#104]
Is there any way to tweak the generated tables and classes names? That is, I am using sqlacodegen within a Flask Open API application. The problem is that the Open API classes have the same names as the database tables. Therefore, I would like the sqlacodegen tables to be prepended with `Db` for example. That way, my Flask model `User` would be different than my sqlalchemy model `DbUser` for instance. I can't seem to find a solution to this.

**Comment by agronholm** [comment]
Currently, this is possible by overriding `generate_model_name()`. Be warned, however, that the API might change before v3.0 final.
