### ISSUE TITLE
Implements server default values ​​that do not exist

### ISSUE THREAD

**Issue by danielahdez** [agronholm/sqlacodegen#111]
I am generating models from different databases, some pk do not indicate a default value in case of null, and the sqlacodegen is generating them as if they had a server default value even if they don't have it, it brings me problems in my logic

**Comment by agronholm** [comment]
Could you show me the table definition and the generated code please?

**Comment by agronholm** [comment]
I have tested this and found no problems. With no way to reproduce this and no answer given in 3+ months, I'm closing this.
