### ISSUE TITLE
Naming collisions between class attributes and imported SQLAlchemy functions

### ISSUE THREAD

**Issue by ongopongo** [agronholm/sqlacodegen#114]
### Background:

The `sqlacodegen` tool generates Python classes that contain attributes, where the names of the attributes match the names of columns in a database table. The tool also generates Python `import` statements (at the top of the file).

One of the functions that can be imported in one of those `import` statements is named `text` (which can then be invoked via `text()`). Similarly, another one of the functions that can be imported is named `relationship` (which can then be invoked via `relationship()`).

### Problem:

A database table can have a column named `text`. Similarly, a database table can have a column named `relationship`. When that happens, the tool will define an attribute named `text` and/or `relationship`. That is the normal behavior of the tool.

However, the generated column attribute definitions sometimes involve invoking the imported function named `text` to specify a default value for the column. The problem is, by the time `text` gets invoked there, the symbol is actually referring to a previously-defined attribute named `text` instead of the function named `text` that was imported.

For example:

```py
from sqlalchemy import Boolean, Column, Text, text
from sqlalchemy.dialects.postgresql import UUID

# ...

class Foo(Base):
    __tablename__ = 'Foo'

    _id = Column(UUID, primary_key=True)
    text = Column(Text)

    # `text` now refers to the class attribute, not the imported function!

    isSomething = Column(Boolean, nullable=False, server_default=text("false"))
    #                                                            ^^^^
```

Similarly, the generated classes sometimes invoke the imported function named `relationship`. This leads to a analogous problem:

```py
from sqlalchemy import Boolean, Column, String, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

# ...

class Bar(Base):
    __tablename__ = 'Bar'

    _id = Column(UUID, primary_key=True)
    relationship = Column(String(255))

    # `relationship` now refers to the class attribute, not the imported function!

    User = relationship('User')
    #      ^^^^^^^^^^^^
```

### Proposal:

I fixed this manually in my own project, by (1) inserting the following code after the `import` statements and before all the `class` definitions:

```py
# Aliases for some imported symbols, in case `sqlacodegen` defines a class attribute having the name shown on the right:
text_ = text
relationship_ = relationship
```

Then (2) updating the problematic invocations of `text` and `relationship` to use `text_` and `relationship_` instead (which were _not_ overwritten because the database does not happen to contain columns named `text_` nor `relationship_`).

For example:

```py
    isSomething = Column(Boolean, nullable=False, server_default=text_("false"))
    #                                                            ^^^^_
```

and

```py
    User = relationship_('User')
    #      ^^^^^^^^^^^^_
```

My proposal is that this tool be updated to check for naming conflicts and, if found, to either use aliases for the imported functions, as I have done manually; or to prefix the imported functions with something like `sacg` (an acronym for this package) by using `as` in the imports; or to just import `sqlalchemy` and reference the sub-symbols using dots (so every imported thing is referenced with `sqlalchemy.<something>`, which I don't think will ever conflict with a class attribute's name).

### Appendix:

Thanks for developing this tool and making it available to the world! I used it for the first time yesterday to generate models that map to an existing database and (once I figured out the issue and fix I described above) was/am happy with the code it generated. I'm planning to propose to my team that running it be part of our normal workflow whenever someone modifies the database schema (which is used by multiple projects). Currently, that would also involve applying the naming collision fix I described above.

**Comment by agronholm** [comment]
Thanks!

I think that the proper way to fix the collision issues is to assign names to tables, classes, columns and relationships only after they have all been generated. I will look into including that fix in v3.0.
