### ISSUE TITLE
Bug with computed columns

### ISSUE THREAD

**Issue by neriusmika** [agronholm/sqlacodegen#116]
When I have computed columns in sql server defined as:
`[CHTIME]  AS (case when [DOCUMENTURLCREATETIME]>[SENDTIME] then [DOCUMENTURLCREATETIME] else [SENDTIME] end)`

sqlacodegen raises exception:
`  File "...\lib\site-packages\sqlacodegen\codegen.py", line 569, in render_column
    default_expr = self._get_compiled_expression(column.server_default.arg)
AttributeError: 'Computed' object has no attribute 'arg'`

**Comment by agronholm** [comment]
Could you tell me how to repro this win an open source RDBMS so I could add a regression test?

**Comment by smartswdeveloper** [comment]
You could try with SQL Server Express (not open source, but free):
https://www.microsoft.com/en-us/sql-server/sql-server-downloads

and here you have some examples
https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver15#:~:text=A%20computed%20column%20is%20a,in%20SQL%20Server%202019%20(15.

**Comment by zzzeek** [comment]
Hi @agronholm -

You can create a computed column default on postgresql 12, or recent versions of sqlite and MySQL/mariadb .  Sqlalchemy supports all these backends, need the 1.3.18 for sqlite.

https://docs.sqlalchemy.org/en/13/core/defaults.html?highlight=computed#computed-ddl

**Comment by zzzeek** [comment]
specifically PG 12, MySQL 5.7, SQLite 3.31:

```
from sqlalchemy import Column
from sqlalchemy import Computed
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import MetaData
from sqlalchemy import Table

metadata = MetaData()

square = Table(
    "square",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("side", Integer),
    Column("area", Integer, Computed("side * side")),
    Column("perimeter", Integer, Computed("4 * side")),
)


e = create_engine("mysql://scott:tiger@localhost/test", echo=True)


metadata.create_all(e)

```

```

sqlacodegen mysql://scott:tiger@localhost/test
Traceback (most recent call last):
  File "/home/classic/.venv3/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/home/classic/.venv3/lib/python3.8/site-packages/sqlacodegen/main.py", line 53, in main
    generator.render(outfile)
  File "/home/classic/.venv3/lib/python3.8/site-packages/sqlacodegen/codegen.py", line 699, in render
    rendered_models.append(self.render_class(model))
  File "/home/classic/.venv3/lib/python3.8/site-packages/sqlacodegen/codegen.py", line 679, in render_class
    self.indentation, attr, self.render_column(column, show_name))
  File "/home/classic/.venv3/lib/python3.8/site-packages/sqlacodegen/codegen.py", line 573, in render_column
    default_expr = self._get_compiled_expression(column.server_default.arg)
AttributeError: 'Computed' object has no attribute 'arg'

```
