### ISSUE TITLE
Snowflake support? "Table 'APPLICABLE_ROLES' does not exist or not authorized."

### ISSUE THREAD

**Issue by adamerose** [agronholm/sqlacodegen#117]
Can anyone confirm if this library works with Snowflake? When I try it myself I get the error below, but not sure if Snowflake is completely unsupported or there is a problem with my database that I can fix.

```Python
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002003 (42S02): SQL compilation error:
Table 'APPLICABLE_ROLES' does not exist or not authorized. [SQL: 'DESCRIBE TABLE /* sqlalchemy:get_primary_keys */ APPLICABLE_ROLES'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by agronholm** [comment]
I have never heard of this Snowflake. Does this happen during schema reflection?

**Comment by adamerose** [comment]
Actually I tried some more since I made this and ended up getting it working, the error was due to lack of permissions and fixed by just specifying a role and warehouse in the database URL.

> I have never heard of this Snowflake. 
It's a cloud data warehouse SQL service
https://db-engines.com/en/system/Snowflake
