### ISSUE TITLE
Is that possible the models only use the generic type?

### ISSUE THREAD

**Issue by GaryChiang** [agronholm/sqlacodegen#118]
Hi folks,

I'm dealing with generating model from an existing mysql database.

I got type declaration below: 

--------------
from sqlalchemy import CheckConstraint, Column, Date, DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.mysql import BIGINT, DATETIME, INTEGER, LONGTEXT, SMALLINT, TINYINT
--------------

Is it possible only to use the generic type? 

Because sometimes we need to migrate our table schema to different type database eg. MSSQL or Oracle. 

So maybe when we generate tables to Oracle type database by using this models script, it may causes some errors. 

Thanks for your time

**Comment by agronholm** [comment]
The code generator does its best to infer the generic types, but that's not always possible. If you can think of a way to improve its logic, please send a PR with accompanying test(s).

**Comment by agronholm** [comment]
Since it's been 1½ years without a response, I'm closing this. If you would like me to work on this, please paste the table definition(s) on the MySQL side that generate these, and the resulting code and the used sqlacodegen version.
