### ISSUE TITLE
Auto Increment Seq not created

### ISSUE THREAD

**Issue by matthewbal** [agronholm/sqlacodegen#122]
I used this amazing library to auto create a bunch of models from a huge Django Postgres database and it worked amazingly on the first try.
The only thing it missed was the auto sequences.

On every table, it correctly generated the "id" with the following definition (note, there are many non-django tables in this project too, these all have the same issue)

```
class DjangoMigration(Base):
    __tablename__ = 'django_migrations'

    id = Column(Integer, primary_key=True, server_default=text("nextval('django_migrations_id_seq'::regclass)"))
```

Unfortunately when I went to use this model to create a new table, I get the following issue:

```
E   sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "django_migrations_id_seq" does not exist
```

The workaround is to add the following into each table definition:
```
class DjangoMigration(Base):
    __tablename__ = 'django_migrations'

    django_migrations_id_seq = Sequence('django_migrations_id_seq', metadata=Base.metadata)

    id = Column(Integer, primary_key=True, server_default=text("nextval('django_migrations_id_seq'::regclass)"))
```

It'd be great if this library had auto created those lines as well! This could be user error, but I thought I'd report it in case there's a bug present.

Using:
Python 3.6.11 (official docker image)
postgres:11 (official docker image)
sqlacodegen 2.3.0 (pypi)

psycopg2==2.8.5
SQLAlchemy==1.3.19
SQLAlchemy-Utils==0.36.8

**Comment by AntonOfTheWoods** [comment]
Given that it appears that such sequences get created automatically in many cases when a column is a singular primary key of type `Integer`, I just did a replace of `/, server_default.*)")//`. Might there be some drawbacks to this approach?

**Comment by agronholm** [comment]
It's pretty difficult for sqlacodegen to determine if sequences should be declared explicitly or not. In this particular case I'm guessing that you used the generated metadata to create a new database and that's why you had the problem?

This could be added as an option I suppose.

**Comment by agronholm** [comment]
Are sequences even reflected? How can I find them in the metadata?
