### ISSUE TITLE
The model class generated by sqlacodegen has no __repr__ method. How to include this method in the generated class automaticly.

### ISSUE THREAD

**Issue by qtbhappy** [agronholm/sqlacodegen#123]
The model class generated by sqlacodegen has no __repr__ method. Could someone tell us how to include this method in the generated class automaticly.

**Comment by LostInDarkMath** [comment]
I would be very happy too, if their would be an auto-generated `__repr__()` method in each class.

**Comment by LostInDarkMath** [comment]
@qtbhappy I created a hacky workaround for this:
```python
from sqlalchemy.orm.state import InstanceState


def add_repr_method(cls):
    def repr_func(self) -> str:
        dict_without_self = {}
        for k in self.__dict__:
            if not isinstance(self.__dict__[k], InstanceState):
                dict_without_self[k] = self.__dict__[k]
        return str(dict_without_self)

    setattr(cls, '__repr__', repr_func)
    return cls


if __name__ == '__main__':
    import_str = 'from src.db_model_decorator import add_repr_method\n'   # change this to your file
    result = [import_str]

    with open('db_model.py', mode='r') as file:
        content = file.readlines()

        if content[0] == import_str:
            exit()

        for line in content:
            if line.startswith('class'):
                result.append('@' + add_repr_method.__name__ + '\n')
            result.append(line)
        print(result)

    with open('db_model.py', mode='w') as file:
        file.writelines(result)
```
Just run this script every time after you run `sqlacodegen`. Hope that helps.

**Comment by qtbhappy** [comment]
> @qtbhappy I created a hacky workaround for this:
> 
> ```python
> from sqlalchemy.orm.state import InstanceState
> 
> 
> def add_repr_method(cls):
>     def repr_func(self) -> str:
>         dict_without_self = {}
>         for k in self.__dict__:
>             if not isinstance(self.__dict__[k], InstanceState):
>                 dict_without_self[k] = self.__dict__[k]
>         return str(dict_without_self)
> 
>     setattr(cls, '__repr__', repr_func)
>     return cls
> 
> 
> if __name__ == '__main__':
>     import_str = 'from src.db_model_decorator import add_repr_method\n'   # change this to your file
>     result = [import_str]
> 
>     with open('db_model.py', mode='r') as file:
>         content = file.readlines()
> 
>         if content[0] == import_str:
>             exit()
> 
>         for line in content:
>             if line.startswith('class'):
>                 result.append('@' + add_repr_method.__name__ + '\n')
>             result.append(line)
>         print(result)
> 
>     with open('db_model.py', mode='w') as file:
>         file.writelines(result)
> ```
> 
> Just run this script every time after you run `sqlacodegen`. Hope that helps.

Thank you very much.

**Comment by agronholm** [comment]
You can do this in master by subclassing `DeclarativeGenerator` and overriding `render_class()`. Note, however, that the API might change before v3.0 final.
