### ISSUE TITLE
Allow to use with automap_base

### ISSUE THREAD

**Issue by olivierdalang** [agronholm/sqlacodegen#128]
Hi !

Awesome library !

It's not clear however if/how this is related to automap_base ? In our use case, we already use automap_base, and would like to "bake" these to python scripts. In particular, we have configured `name_for_collection_relationship` and `name_for_scalar_relationship`, and would need those to be used for relationship names.

Is that possible ? It means calling the library from code rather than command line, like this :
```python
from sqlacodegen.codegen import CodeGenerator
from sqlalchemy import create_engine
from sqlalchemy.ext.automap import automap_base
from .utils import my_custom_name_for_collection_relationship, my_custom_name_for_scalar_relationship

engine = create_engine(...)

Base = automap_base()

# Potentially manually define some classes relations here
# see https://docs.sqlalchemy.org/en/13/orm/extensions/automap.html#specifying-classes-explicitly

Base.prepare(
        engine 
        reflect=True,
        schema=schema,
        # see https://docs.sqlalchemy.org/en/13/orm/extensions/automap.html#sqlalchemy.ext.automap.AutomapBase.prepare.params.name_for_scalar_relationship
        name_for_collection_relationship=my_custom_name_for_collection_relationship,
        name_for_scalar_relationship=my_custom_name_for_scalar_relationship,
)

Base.metadata.bind(engine)
generator = CodeGenerator(Base.metadata)
generator.render(open('output.py', 'w', encoding='utf-8'))

```

Unfortunately, while this generates code, it seems it doesn't use the custom names. From a very quick look at the code, it looks like sqlacodegen does it's own relationship detection, not using automap_base at all.

**Comment by agronholm** [comment]
Automap is an alternative to sqlacodegen. The downside is that the database schema has to be reflected each time the app starts, and it doesn't work with static code checkers. So "allowing use with automap_base" makes no sense here.
