### ISSUE TITLE
Usage instructions for citext support not working

### ISSUE THREAD

**Issue by wilcoln** [agronholm/sqlacodegen#130]
Hello,

I've been trying to enable citext support by following the installation instructions in the README.md file, however it is not working, as you can see in the screenshot below.

![Screenshot from 2021-02-15 13-31-53](https://user-images.githubusercontent.com/24209192/107947254-71cb7680-6f92-11eb-8bdf-df7a55c4467a.png)

Edit: I'm on Ubuntu 18.04

**Comment by mzpqnxow** [comment]
@wilcoln are you still having this issue?

**Comment by mzpqnxow** [comment]
try this:

```
$ pip uninstall sqlacodegen
$ pip install 'git+https://github.com/agronholm/sqlacodegen@master#egg=sqlacodegen[citext]'
```

If that works, then try:

```
$ pip uninstall sqlacodegen
$ pip install 'sqlacodegen[citext]'
```

That solved the issue for me, though I had a weird configuration (I had a constraints file pointing at my own fork)

**Comment by wilcoln** [comment]
@mzpqnxow No I'm not, thanks for your input.
