### ISSUE TITLE
看起來好像是編碼錯誤。 It seems to be a coding error.

### ISSUE THREAD

**Issue by swdcgghxa** [agronholm/sqlacodegen#136]
抱歉，我英文不怎麼好，所以我用Google翻譯。
Sorry, my English is not very good, so I use Google Translate.

我也不知道發生了甚麼。
I don't know what happened.

我使用的範例資料庫。
The sample database I use.

**DataBase**
http://www.yiibai.com/downloads/yiibaidb.zip

**來源 (source)**
https://www.yiibai.com/mysql/how-to-load-sample-database-into-mysql-database-server.html

正常的匯出
I export normally

````bat
poetry run sqlacodegen mariadb+mariadbconnector://root:pw@127.0.0.1:3306/yiibaidb > yiibaidb_models.py
````

我得到的錯誤。
The error i get.

```
UnicodeEncodeError: 'cp950' codec can't encode character '\u4ea7' in position 2098: illegal multibyte sequence
```

能幫我嗎感謝。
Can you help me thanks.

**Comment by agronholm** [comment]
Have you tried using unicode (utf8mb4 on MySQL) instead of cp950 as the character set?

**Comment by agronholm** [comment]
Closed due to lack of response.
