### ISSUE TITLE
generating classes containing column names with '$' prefix and foreign key relationships

### ISSUE THREAD

**Issue by nathanjshaffer** [agronholm/sqlacodegen#138]
I have a schema in mysql that I have used sqlacodgen to generate the classes for.  Here is one example.  

code:

    class Email(Base):
        __tablename__ = 'email'

        id = db.Column(db.Integer, primary_key=True)
        email = db.Column(db.String(128, 'utf8mb4_0900_ai_ci'), nullable=False)
        _contact_info_id = db.Column('$contact_info_id', db.ForeignKey('contact_info.id'), nullable=False, index=True)

        _contact_info = db.relationship('ContactInfo', primaryjoin='Email.$contact_info_id == ContactInfo.id')

In this you will notice that in the relationship line, it incorrectly generates the join column 'Email.$contact_info_id'
I have my database naming settings set so that any foreign key column is named with a $ prefix.  sqlacodegen correctly strips this from all of the class members and replaces with an underscore, except in the db.relationship it retains the invalid characters.  I have to do a regex replace in all of the generated models to correct this whenever I regenerate models for a database.

**Comment by agronholm** [comment]
This should be resolved by 6af0f02de75152b433c0ae2bca757d51e0387958.
