### ISSUE TITLE
[Question] Why sqlacodegen not generating non-public tables?

### ISSUE THREAD

**Issue by miriam-z** [agronholm/sqlacodegen#144]
Tables are:

cam*****.city_tier <--- Not generated
cam****.targets.   <--- Not generated
public.**city.         <-- Generated
public.reports.     <-- Generated

sqlacodegen only generates classes for public.* tables but not non-public tables?  

or certain flags need to be defined when using sqlacodegen?

**Comment by agronholm** [comment]
By default, only tables from the default search path are generated. Otherwise you will have to specify which schema to look at, using `--schema`.

**Comment by miriam-z** [comment]
sqlacodegen 'postgresql://user:password@host.io:5437/database'  --schema XXXX.targets
```
# coding: utf-8
from sqlalchemy import MetaData

metadata = MetaData()
```

But it is expecting to return the class or table just like others

**Comment by agronholm** [comment]
What is expecting to return that? Are you saying that no tables or classes are generated? Please elaborate.

**Comment by miriam-z** [comment]
just updated above

**Comment by agronholm** [comment]
I don't understand your question. I still don't understand what "it" refers to here. What is the problem? Are some tables or classes missing?

**Comment by miriam-z** [comment]
Saying that only tables from 

public.reports
public.user 

are generated

but 

camdummy.targets
camdummy.report

are not

so tried to use the --schema suggested but the output is 

```
from sqlalchemy import MetaData

metadata = MetaData()

```

**Comment by agronholm** [comment]
Ah, okay. It would seem that the user account in question may not have proper access to these schemas.

Try the following code:

```python3
    from sqlalchemy import create_engine, MetaData

    engine = create_engine('postgresql://user:password@host.io:5437/database')
    metadata = MetaData()
    metadata.reflect(engine, 'camdummy.targets')
    for table in metadata.sorted_tables:
        print(table)
```
What does that output?

**Comment by miriam-z** [comment]
empty so far

**Comment by miriam-z** [comment]
For example in standard query:

![Screenshot 2021-07-18 at 12 00 18](https://user-images.githubusercontent.com/19760229/126064654-84d9450e-a72e-4605-bfee-f24eea3d04c7.png)

**Comment by miriam-z** [comment]
For example in SQL query:

![Screenshot 2021-07-18 at 12 01 42](https://user-images.githubusercontent.com/19760229/126064697-b817fce1-1ac1-41a5-874d-82b1d3d57c5a.png)

**Comment by agronholm** [comment]
I don't know what to do about this. If there are no tables after reflection, then sqlacodegen won't have any data to work with. Adding `echo=True` to `create_engine()` should echo the exact SQL used by sqlalchemy to reflect the schema. That may provide some hints as to what is going wrong.

**Comment by agronholm** [comment]
Note that having `select` privileges on a table does not necessarily mean that you have the proper permissions for introspecting its schema.

**Comment by agronholm** [comment]
By specifying `--schemas` you can reflect all the schemas you need. I'm closing this as the question has hopefully been answered, at least for sqlacodegen.
