### ISSUE TITLE
[Question] Why only public.* tables are generated?

### ISSUE THREAD

**Issue by scheung38** [agronholm/sqlacodegen#145]
Also, why classes and tables are generated from only public.* tables in my case, but all non-public.* tables are not generated?
![Screenshot 2021-07-17 at 15 31 03](https://user-images.githubusercontent.com/1273014/126040259-8d4ee96c-e2e4-47d6-b57e-71ccd1a18dd1.png)

must I need to specify the --table flag followed by the name of the table?

**Comment by agronholm** [comment]
Are you with the same group as the one who posted #144? I'd appreciate having only one open issue for each question.
