### ISSUE TITLE
[Question] Why each time generate different data model even the postgresql server is not change?

### ISSUE THREAD

**Issue by saxontseng** [agronholm/sqlacodegen#146]
Hi sir,

I find when I use the sqlacodegen to generate the ORM data model, even I do not change anything from postgresql server,
when I do twice sqlacodegen, the result files use diff looks like different because the class sequence/order always change every time(althrough the file size is the same and all data model is the same), does any chance to let it the same? Since it is not suit for version control.

Below is my pip list environment:
sqlacodegen (2.3.0)
SQLAlchemy (0.9.8)
SQLAlchemy-Utils (0.32.14)

Or it is not cause by sqlacodegen but SQLAlchemy version problem?

**Comment by agronholm** [comment]
You are using a very old version of SQLAlchemy. Try upgrading and see if the results are more consistent.
