### ISSUE TITLE
Allow specification of a custom column-naming function

### ISSUE THREAD

**Issue by dhirschfeld** [agronholm/sqlacodegen#147]
This is a similar request to #112, #76, #142 except I'd like the ability to customise the naming of the columns from Python - e.g.
https://docs.sqlalchemy.org/en/14/orm/mapping_columns.html#naming-columns-distinctly-from-attribute-names

**Comment by dhirschfeld** [comment]
I [note](https://github.com/agronholm/sqlacodegen/pull/112#issuecomment-877683169) that a refactoring is underway so I'm opening this issue in the hope that this use-case may be considered.

**Comment by agronholm** [comment]
Commit ba08a71e2c85207ffedee52a6541e9b7df07f9d4 added the ability to do this by overriding `generate_column_attr_name()`.

**Comment by dhirschfeld** [comment]
Thanks @agronholm! I look forward to trying it out...

**Comment by agronholm** [comment]
You can try it out now – 3.0.0b1 is out.
