### ISSUE TITLE
Stripped s at the end of the class name

### ISSUE THREAD

**Issue by vector400** [agronholm/sqlacodegen#148]
It seems if a table ends with an `s` the s is not included to the class name.
E.g.:
orders -> Order
customers -> Customer
customer_status -> CustomerStatu

I understand the idea behind it, as some people name their table in plural. I think this is in general a bad practice, a table should be named by the meaning of a single record (e.g. "order" instead of "orders"), especially when using ORM. There might even be situations where I want a table where each record represents multiple things (shouldn't be that common but it may happen, e.g. there is a table 'playlists' which groups entries of the table 'playlist' by some criteria). 
Also, when the table ends with s without meaning the plural (e.g. anything with _status) this might lead to confusing behavior. 

I´d appreciate at least an option to control this behavior. If wanted (and I find some free time) im willing to open a PR myself for the implementation.

**Comment by ikzelf** [comment]
My guess is that this is giving even funnier effects in other languages. Many programs/databases have local names in them. Messing with the names to try to take the plural form out of it looks to me like a different task and to keep this simple I would go for: don't mess with the names, just copy them in the original form. The snake<>camel I have no opinion on. What I see now looks ok.
[Plural Nouns in German Grammar](https://deutsch.lingolia.com/en/grammar/nouns-and-articles/plural)

**Comment by vector400** [comment]
My bad, this option already exists 🤦.
`--noinflect` it is...
