### ISSUE TITLE
Invalid python code if a postgres view has a comment that contains a newline

### ISSUE THREAD

**Issue by takar** [agronholm/sqlacodegen#156]
If a comment on a postgres view contains a newline, the generated python code is invalid. Example:

```
t_v_test = Table(
    'v_test', metadata,
    Column('id', BigInteger),
    Column('name', String(25)),
    comment='This
is a multi-line
comment'
)
```

Tested with version 2.3.0

**Comment by agronholm** [comment]
I cannot reproduce this on either 2.3.0 or 3.0.0b2. I created a test which passes:
```python3
def test_multiline_comment(metadata) -> None:
    Table(
        'simple_items', metadata,
        Column('id', INTEGER, comment='This\nis a multi-line\ncomment')
    )

    assert generate_code(metadata) == """\
# coding: utf-8
from sqlalchemy import Column, Integer, MetaData, Table

metadata = MetaData()


t_simple_items = Table(
    'simple_items', metadata,
    Column('id', Integer, comment='This\\nis a multi-line\\ncomment')
)
"""
```
I also verified that in both 2.x and 3.x, the `comment` argument is rendered using `repr()` which escapes all newlines.

**Comment by takar** [comment]
Thank you very much for looking into this. I made a minimal example using one table with one column only (PostgreSQL)

```sql
CREATE TABLE IF NOT EXISTS public.test
(
    test "char"
);

# This fails
COMMENT ON TABLE public.test
    IS 'This
is a multi-line
comment';

# This works
COMMENT ON COLUMN public.test.test
    IS 'This
is a multi-line
comment';
```

Running sqlacodegen on this database generates the following result:
```python
t_test = Table(
    'test', metadata,
    Column('test', String, comment='This\nis a multi-line\ncomment'),  # Works
    comment='This
is a multi-line
comment'  # Invalid python code
)
```

I'm currently using this on a legacy database which contains roughly 800 tables and apart from this issue it is working really well. Thanks for your efforts!

**Comment by agronholm** [comment]
Ah, I see – I misread the report. It's about table/view level comments, not column comments.

**Comment by agronholm** [comment]
I added a test for that too and it passes just fine. I'll do one more test against a real database.

**Comment by agronholm** [comment]
Ah, a multiline table comment fails on 2.3.0 but not 3.0.0b2 which is based on master, so I consider this fixed.
