### ISSUE TITLE
Error when compiling dataclass

### ISSUE THREAD

**Issue by canine-afficionado** [agronholm/sqlacodegen#164]
Hi, just started using your product - thanks for all your hard work.

I just tried generating data classes from an MS SQL schema and it worked well except I get the following error when trying to run:

TypeError: non-default argument 'Files' follows default argument

I believe this is because of the last note here: https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass

The field itself is nullable. 

Is this something that can be rectified?

Thanks.

python 3.9, sqlacodegen 3.0.0b2

**Comment by agronholm** [comment]
Would you mind sharing the table that triggered the problem?

**Comment by agronholm** [comment]
Just pasting the generated class would help.

**Comment by WhoAteDaCake** [comment]
I'm having the same problem with:

```python
@mapper_registry.mapped
@dataclass
class UIProjectAlias:
    __tablename__ = 'UI_ProjectAlias'
    __sa_dataclass_metadata_key__ = 'sa'

    Id: int = field(init=False, metadata={'sa': Column(Integer, Identity(start=1, increment=1), primary_key=True)})
    ProjectId: int = field(metadata={'sa': Column(ForeignKey('UI_Project.Id'), nullable=False)})
    Title: str = field(metadata={'sa': Column(String(200, 'SQL_Latin1_General_CP1_CI_AS'), nullable=False)})
    Type: str = field(metadata={'sa': Column(String(20, 'SQL_Latin1_General_CP1_CI_AS'), nullable=False)})
    Website: Optional[str] = field(default=None, metadata={'sa': Column(String(2000, 'SQL_Latin1_General_CP1_CI_AS'))})

    UI_Project: UIProject = field(metadata={'sa': relationship('UIProject', back_populates='UI_ProjectAlias')})
```

@agronholm

**Comment by agronholm** [comment]
Ok, so this is about relationship attributes. That makes sense. I'll try to sort this out soon-ish.

**Comment by WhoAteDaCake** [comment]
Swapping `UI_Project` and `Website` seems to fix it
