### ISSUE TITLE
generated Error when there is computed virtual column

### ISSUE THREAD

**Issue by BridgeWind** [agronholm/sqlacodegen#168]
![image](https://user-images.githubusercontent.com/45143983/145548078-95233561-5fad-460d-8628-5dd45bf2a0e3.png)
Column should be in the order like Column(*args,**kwargs), so for generating column like this, unique = True should be in the place after "Computed(......)" 
It should be like this:
 Column(CHAR(32), Computed("(md5(concat_ws('.',ifnull(`position_id`,0)，ifnull(`h)", persisted=False),unique=True)

**Comment by agronholm** [comment]
This is on 3.0.0b2?

**Comment by BridgeWind** [comment]
sqlacodegen==2.3.0 xD

**Comment by agronholm** [comment]
Would you mind trying with the beta?

**Comment by BridgeWind** [comment]
I'll try xD, just notice we got beta version... orz

**Comment by BridgeWind** [comment]
Great! Works fine for 3.0.0b2

**Comment by agronholm** [comment]
Closing as duplicate of #165.
