### ISSUE TITLE
Invalid python code generated when tables have same name in different schemas

### ISSUE THREAD

**Issue by laurentS** [agronholm/sqlacodegen#169]
I am running the `declarative` code generator on a db with several schemas. I run the generator separately for each schema, so I get one python file per schema.

Two of the schemas `public` and `bb` have foreign keys across them, so the generator pulls in some extra tables from the other schema (so I end up with a few tables doubly declared, which I can live with).

However, some tables have the same name in both schema, something like:
```sql
create table public.mytable (
   id uuid primary key,
   morestuff text
 );
 create table bb.mytable (
   id uuid primary key references public.mytable(id),
   otherstuff text
 );
```

When I generate for schema `bb` with `sqlacodegen --generator declarative $DATABASE_URL --schema bb`, I end up with:
```python
from sqlalchemy import Column, ForeignKeyConstraint, PrimaryKeyConstraint, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Mytable(Mytable):
    __tablename__ = 'mytable'
    __table_args__ = (
        ForeignKeyConstraint(['id'], ['mytable.id'], name='mytable_id_fkey'),
        PrimaryKeyConstraint('id', name='mytable_pkey'),
        {'schema': 'bb'}
    )

    id = Column(ForeignKey('mytable.id'))
    otherstuff = Column(Text)
```

Note the parent class, which makes the code invalid. I cannot import `Mytable`.

I am not sure why this is happening.

EDIT: Updated the above with postgres 12, sqlalchemy 1.4.29 et psycopg2-binary 2.9.3, sqlacodegen c0772c5 as per your questions

**Comment by agronholm** [comment]
What command did you use to generate this?

**Comment by agronholm** [comment]
Also please paste the full set of classes generated.

**Comment by laurentS** [comment]
I updated the description above after retrying with the latest version of the code. The problem is still present.
