### ISSUE TITLE
Invalid Sequence in generated code

### ISSUE THREAD

**Issue by laurentS** [agronholm/sqlacodegen#176]
With the following db in postgres:
```sql
create table seqtest (id serial);
```
and using `sqlacodegen --generator declarative $DATABASE_URL --schema public > public.py`, I get the following generated code:
```python
from sqlalchemy import Column, Integer, MetaData, Sequence, Table

metadata = MetaData()


t_seqtest = Table(
    'seqtest', metadata,
    Column('id', Integer, Sequence('"public".seqtest_id_seq'), nullable=False),
    schema='public'
)
```

Then if I execute `insert(t_seqtest))`, I get the following error in python:
```
Traceback (most recent call last):
  File "/home/laurent/Sites/ovio/sqlacodegen/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/laurent/Sites/ovio/sqlacodegen/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation ""public".seqtest_id_seq" does not exist
LINE 1: INSERT INTO public.seqtest (id) VALUES (nextval('"""public""...
```

which goes away if I replace the sequence definition with:
```python
    Sequence('seqtest_id_seq', schema='public')
```

Looking at the code in `sqlacodegen`, this sequence should not even be generated, but the test fails here: `if match.group(1) != f'{column.table.name}_{column.name}_seq':` because the match seems to include the schema name.

Running this with postgres 12, sqlalchemy 1.4.29 et psycopg2-binary 2.9.3, sqlacodegen c0772c5f6b671c296a46857567185ff5a14032af

**Comment by agronholm** [comment]
I was able to reproduce this locally using a real DB, but not with any artificial Table definition yet.

**Comment by laurentS** [comment]
@agronholm thanks for the fix! Unfortunately, I still seem to be having more or less the same issue. I am running the same test SQL with sqlacodegen ea31798f3e59fb933e6241c78e9ac0047ca8b265  and seeing invalid sqlalchemy code being generated:

If I use `create table public.seqtest (id serial);` then the code generated is:
```python
t_seqtest = Table(
    'seqtest', metadata,
    Column('id', Integer, nullable=False),
    schema='public'
)
```
The sequence is gone, but at least the code is valid.
But if I do `create table otherschema.seqtest (id serial);` (note the schema) then I get this code:
```python
t_seqtest = Table(
    'seqtest', metadata,
    Column('id', Integer, Sequence('otherschema.seqtest_id_seq'), nullable=False),
    schema='otherschema'
)
```
which is invalid. I get the exact same error as in the issue above. The solution again is to add the `schema='otherschema'` option to `Sequence` and drop the schema from the name. I'm now running on sqlalchemy 1.4.35 if it makes any difference.

**Comment by agronholm** [comment]
Yes, I can reproduce this. I'll fix this before the next pre-release.

**Comment by agronholm** [comment]
The problem occurred because I was expecting double quotes around the schema name but they were not present in this case.
