### ISSUE TITLE
new pypi releases?

### ISSUE THREAD

**Issue by Distortedlogic** [agronholm/sqlacodegen#183]
I had to build from source to use the `--generator dataclasses` .. seems a new version hasnt been released to pypi since 2020?? Thanks for the package tho! its super helpful

**Comment by agronholm** [comment]
Where are you looking? https://pypi.org/project/sqlacodegen/3.0.0b3/

**Comment by Distortedlogic** [comment]
Thats what I was looking for. A pypi search for sqlacodegen does not have this link in the results fyi. A note with link in the docs for 2.3.0 would be helpful :)

**Comment by agronholm** [comment]
Yes, it's the same for all projects in PyPI. 3.0.0b3 is a pre-release which are not show in the search results.
