### ISSUE TITLE
UUID columns are cast to any

### ISSUE THREAD

**Issue by Distortedlogic** [agronholm/sqlacodegen#184]
My `id` columns are `Column(UUID)` but are being cast as `Any` with dataclasses. This means all the relation id columns are cast to `Any` as well. This quickly adds up to a lot of `Any`s. Could it be cast to `str` instead?

**Comment by agronholm** [comment]
I recall that there was a problem with `python_type` in UUID columns since they have an option to be represented as either `uuid.UUID` or `str`. I'll look into this.

**Comment by Distortedlogic** [comment]
awesomeness. maybe a cli flag for the dev to choose which one specifically throughout or as `Any`? As a matter of convenience, feels reasonable to assume if said dev uses one type for a column then the others will be the same type. If they are mixing `uuid.UUID` and `str` then id say thats on them and they can have fun with their `Any` typing lol
