### ISSUE TITLE
import name/column name conflict plus metadata column name conflict

### ISSUE THREAD

**Issue by Distortedlogic** [agronholm/sqlacodegen#185]
When the name of something imported is the same as the name of a column, and said column comes before import call inside class, a conflict occurs and the column gets called instead of the import.
![20-03-2022-08-45-01](https://user-images.githubusercontent.com/54854447/159162939-183df809-a946-4528-bf8a-826e4dafd25c.png)
![20-03-2022-08-45-32](https://user-images.githubusercontent.com/54854447/159162957-0daa30c1-dfd9-4191-92c4-64b826511b56.png)

A kinda similiar error occurs with `metadata` in that a column named `metadata` conflicts with the metadata attr for the table, which raises exception.

I did look through the source code to see if I could contribute since ive opened multiple issues and like seriously need this package for quality of life. Unfortunately, its takes a bit more than I know to fix these issues and PR. Tho with my limited understanding it seems possible to check the column names against imports and other reserved attr names, then make the column name slightly different in the class/dataclass or alias import name? I like the idea of an underscore suffix.

**Comment by agronholm** [comment]
I've created a test for this that I've marked with `xfail`. 

I'm not sure if I can easily fix this. Aliasing the column attribute would be the easiest approach, if it's doable.

**Comment by agronholm** [comment]
Ok, looks like fixing this is going to be easier than I thought. It was just a problem with all the imports not being collected before column attribute name generation.
