### ISSUE TITLE
AttributeError: 'Identity'

### ISSUE THREAD

**Issue by noliverte** [agronholm/sqlacodegen#187]
Hello,

I'd like to use sqlacodegen to generates the appropriate SQLAlchemy model code of my SQLSERVER database...

I made the following command in my terminal
`sqlacodegen --outfile model.py "mssql+pyodbc://user:pass@server:port/Database""?driver=ODBC Driver 17 for SQL Server"`
or 
`sqlacodegen  "mssql+pyodbc://user:pass@server:port/Database""?driver=ODBC Driver 17 for SQL Server"`

and I have the following error
```
gen.py", line 601, in render_column
    default_expr = self._get_compiled_expression(column.server_default.arg)
AttributeError: 'Identity' object has no attribute 'arg'
```

do you have an idea to fix it ?

Thanks

Oliver

**Comment by agronholm** [comment]
I'll attempt to reproduce this, but it's indeed strange that there is no `arg` attribute. What version of sqlacodegen did you use btw?

**Comment by noliverte** [comment]
Hi,
Thank you for taking your time to answer me I use version 2.3.0

**Comment by agronholm** [comment]
Have you tried the latest beta?

**Comment by noliverte** [comment]
It works but only with table with primary keys. Thanks

**Comment by agronholm** [comment]
Do you mean you still get the same error on 3.x beta?

**Comment by agronholm** [comment]
SQLAlchemy requires mapped classes to have primary keys. I think you will find that such tables are included but as `Table()` constructs rather than classes.

**Comment by noliverte** [comment]
ok I see but there is one last bug in the generation of the external file with sqlacodegen.
This just happens on one table (class) "FactCampaignMarketing" in all my database

`"ForeignKey" is not defined `
![image](https://user-images.githubusercontent.com/2790375/160574890-867cff97-9ac9-406f-9bd5-4875ba945ea7.png)
...
![image](https://user-images.githubusercontent.com/2790375/160573455-67b33af9-d554-4710-8f32-c691c20a8b4b.png)
...
![image](https://user-images.githubusercontent.com/2790375/160573580-da9127a6-8af5-4239-94f8-2afd19be6b2b.png)
...
![image](https://user-images.githubusercontent.com/2790375/160573669-aed58e27-865e-4d0d-ab28-56aa7b4e8002.png)

**Comment by agronholm** [comment]
That's already reported as #182.

**Comment by agronholm** [comment]
Closing as this is already working in the beta.
