### ISSUE TITLE
Generate code for user-defined functions

### ISSUE THREAD

**Issue by amacfie** [agronholm/sqlacodegen#191]
Presumably this would be difficult but it would be useful to auto-generate type-annotated Python functions that call user-defined functions (UDFs) in the db (i.e. things you make with `CREATE FUNCTION`). The name, parameter types and return type would correspond and maybe if there's a comment on the UDF, it could go in a docstring. The body of the Python function would just call the UDF via SQLAlchemy. UDFs can use "composite" types as input or output so we'd also need to generate classes for any composite types found.

**Comment by agronholm** [comment]
My plan for the next major release is to give the user full freedom to generate code as they please. We'll see how much freedom can be reasonably given without complicating sqlacodegen code too much.

**Comment by amacfie** [comment]
https://github.com/amacfie/sqlafunccodegen
