### ISSUE TITLE
column_0_label in convention string

### ISSUE THREAD

**Issue by PaleNeutron** [agronholm/sqlacodegen#192]
```
File /usr/local/lib/python3.10/site-packages/sqlacodegen/utils.py:101, in uses_default_name(constraint)
     98 except KeyError:
     99     return False
--> 101 return constraint.name == (convention % values)

KeyError: 'column_0_label'
```

Debug info:

```
>>> len(constraint.columns)
0
>>> convention
'ix_%(column_0_label)s'
>>> values
{'table_name': 'chinabwmdesc', 'constraint_name': 'idx_chinabwmdesc_03', 'column_0N_name': '', 'column_0_N_name': '', 'column_0N_label': '', 'column_0_N_label': '', 'column_0N_key': '', 'column_0_N_key': ''}
>>> constraint
Index('idx_chinabwmdesc_03')
>>> table.metadata.naming_convention
immutabledict({'ix': 'ix_%(column_0_label)s'})
```

Real index  field in database:
> idx_chinabwmdesc_03: "TO_CHAR("OPDATE",'yyyymmdd')" ASC

SQLAlchemy Version: 1.4.35
database: Oracle 11g

**Comment by agronholm** [comment]
Am I understanding correctly that you have an index that has no columns associated with it? How is that even possible? What is the point of that?

**Comment by agronholm** [comment]
Yes, and I've fixed that in the latest beta. I just don't understand how you have an index in your database that does not have any columns associated with it.

**Comment by PaleNeutron** [comment]
@agronholm , index shown in Navicat is `idx_chinabwmdesc_03: "TO_CHAR("OPDATE",'yyyymmdd')" ASC`
I think it is a function based index which is created by something like:

```
create index IDX_TO_CHAR on emp(to_char(hiredate,'YYYY-MM-DD HH24:MI:SS'));
```

Sqlalchemy reflect it to an `Index` object without any columns associated with it and I can not find out where is the sql stored in the object.

**Comment by agronholm** [comment]
Ok, that makes sense, thanks.
