### ISSUE TITLE
Faulty generation of relationships

### ISSUE THREAD

**Issue by Haladesta** [agronholm/sqlacodegen#201]
I'm having a problem with the relationships generated from v3.0.0rc1.
I'm using PostgreSQL 14 and have the following two tables among others which represent a many-to-many relationship that references itself:

    CREATE TABLE IF NOT EXISTS public.persons
    (
        person_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        first_name text COLLATE pg_catalog."default",
        CONSTRAINT "PK__persons" PRIMARY KEY (person_id)
    )

    CREATE TABLE IF NOT EXISTS public.dont_merge_persons
    (
        person_id_1 bigint NOT NULL,
        person_id_2 bigint NOT NULL,
        CONSTRAINT "PK__dont_merge_persons" PRIMARY KEY (person_id_1, person_id_2),
        CONSTRAINT "FK__dont_merge_persons__person_id_1" FOREIGN KEY (person_id_1)
            REFERENCES public.persons (person_id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
            NOT VALID,
        CONSTRAINT "FK__dont_merge_persons__person_id_2" FOREIGN KEY (person_id_2)
            REFERENCES public.persons (person_id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
            NOT VALID
    )

and I'm using this command to generate the file:
`sqlacodegen <url> --outfile DBTables_Test.py --option use_inflect --option noindexes --generator dataclasses`

when I then try to use it I get the following error:

    Traceback (most recent call last):
        File "C:\Projects\prototyping\venv\lib\site-packages\sqlalchemy\orm\clsregistry.py", line 408, in __call__
        x = eval(self.arg, globals(), self._dict)
        File "<string>", line 1, in <module>
    NameError: name 't_dont_merge_persons' is not defined

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
    ...
    sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class Persons->persons, expression 'Persons.person_id == t_dont_merge_persons.c.person_id_1' failed to locate a name ("name 't_dont_merge_persons' is not defined"). If this is a class name, consider adding this relationship() to the <class 'DatabaseInterface.test.DBTables_Test.Persons'> class after both dependent classes have been defined.

within the Persons-Class it generates these two members

    persons: List[Persons] = field(default_factory=list, metadata={'sa': relationship('Persons', secondary='dont_merge_persons', primaryjoin='Persons.person_id == t_dont_merge_persons.c.person_id_1', secondaryjoin='Persons.person_id == t_dont_merge_persons.c.person_id_2', back_populates='persons_')})
    persons_: List[Persons] = field(default_factory=list, metadata={'sa': relationship('Persons', secondary='dont_merge_persons', primaryjoin='Persons.person_id == t_dont_merge_persons.c.person_id_2', secondaryjoin='Persons.person_id == t_dont_merge_persons.c.person_id_1', back_populates='persons')})

I've figured out that the error is caused by the `primaryjoin` and `secondaryjoin` values because they reference the class-name instead of the table-name so removing the "t_" appears to fix it.

Also I've noticed that use_inflect doesn't seem to do anything

**Comment by agronholm** [comment]
> I've figured out that the error is caused by the primaryjoin and secondaryjoin values because they reference the class-name instead of the table-name so removing the "t_" appears to fix it.

None of the class names contain "t_" so what do you mean? Can you paste the working code here?

**Comment by agronholm** [comment]
It's pretty amazing that this hasn't come up before. I guess self referential many-to-many relationships aren't that common? Anyways, I've fixed the problem by using lambdas instead of string-based expressions.

As far as inflect goes, for me it generates the class `Person` if enabled, and `Persons` if not, so seems to work as advertised? Were you expecting something else?

**Comment by Haladesta** [comment]
> None of the class names contain "t_" so what do you mean? Can you paste the working code here?

Sorry if I wasn't clear enough. I meant replacing the `t_dont_merge_persons.c.person_id_1` with `dont_merge_persons.c.person_id_1`.

> It's pretty amazing that this hasn't come up before. I guess self referential many-to-many relationships aren't that common? Anyways, I've fixed the problem by using lambdas instead of string-based expressions.

Ah, great. Thank you.

> As far as inflect goes, for me it generates the class Person if enabled, and Persons if not, so seems to work as advertised? Were you expecting something else?

Hmm, strange. I'll test it out at some point and possibly report back if I can't get it to work. 
Were you using the identical command?
