### ISSUE TITLE
Missing Imports

### ISSUE THREAD

**Issue by agronholm** [agronholm/sqlacodegen#23]
Originally reported by: **hamx0r (Bitbucket: [hamx0r](https://bitbucket.org/hamx0r), GitHub: [hamx0r](https://github.com/hamx0r))**

----------------------------------------

Using on a Postgres DB acquired Columns of type TEXT, yet TEXT was imported from neither sqlalchemy nor sqlalchemy.dialects.postgres.base

This was run under Windows 7 x64 using iPython as the interpreter.

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/sqlacodegen/issue/23

**Comment by davidthewatson** [comment]
I ran into this with sqlacodegen 1.1.6 in the following generated code:

    allowed_pets = Column(ARRAY(TEXT()))

at runtime, this produces the error:

    NameError: name 'TEXT' is not defined

Inspecting generated imports:

    from sqlalchemy import ARRAY, BigInteger, Boolean, CheckConstraint, Column, Date, DateTime, Float, ForeignKey, Integer, JSON, LargeBinary, Numeric, SmallInteger, String, Text, UniqueConstraint, text
    from sqlalchemy.orm import relationship
    from sqlalchemy.dialects.postgresql.base import UUID
    from sqlalchemy.ext.declarative import declarative_base

**Comment by agronholm** [comment]
I feel like this is a separate issue. The ARRAY type is kind of a special snowflake that requires explicit support. Should add this to the to-do list.
