### ISSUE TITLE
Table without primary key is not class!

### ISSUE THREAD

**Issue by emresekeroglu** [agronholm/sqlacodegen#235]
I have searched many forums, I have looked at the repo, I am not sure if there is a method to fix this situation, what is your suggestion?
Or should I wait for your new updates?

**Comment by agronholm** [comment]
Tables without primary keys can't be mapped as classes, as per the [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/14/faq/ormconfiguration.html#how-do-i-map-a-table-that-has-no-primary-key).
