### ISSUE TITLE
Move to sqlalchemy 2.0 beta

### ISSUE THREAD

**Issue by PaleNeutron** [agronholm/sqlacodegen#236]
I found `sqlalchemy.__all__` does not exist in version 2.0.

**Comment by rbuffat** [comment]
SQLAlchemy 2.0.0 is now released: https://www.sqlalchemy.org/blog/#sqlalchemy-2.0.0-released

**Comment by Henkhogan** [comment]
> I found `sqlalchemy.__all__` does not exist in version 2.0.

https://github.com/agronholm/sqlacodegen/blob/f05d99e2a2a6d04b065ebad4b1d68a69b1e69572/src/sqlacodegen/generators.py#L244

I worked around by changing it to

`elif type_.__name__ in sqlalchemy.__dict__:  # type: ignore[attr-defined]`

**Comment by amacfie** [comment]
Try latest `master`
