### ISSUE TITLE
ModuleNotFoundError: No module named 'pymysql'

### ISSUE THREAD

**Issue by jesperbruunhansen** [agronholm/sqlacodegen#242]
For some reason, I'm not able to run the CLI as I get an exception saying pymysql cannot be imported. But pip list clearly tells me that pymysql is available. Please see outputs below:

Steps carried out to get the following result:
```bash
# 1. Create new venv
python3.10 -m venv sqlacodegen-venv

# 2. Activate venv
source sqlacodegen-venv/bin/activate

#3. Install pymysql
pip install pymysql 

#4. Install sqlacodegen
pip install sqlacodegen

#5. Run CLI
sqlacodegen mysql+pymysql://root:secret@localhost:3306/<schema_name>
```

Output:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/sqlacodegen/main.py", line 44, in main
    engine = create_engine(args.url)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 68, in dbapi
    return __import__("pymysql")
ModuleNotFoundError: No module named 'pymysql'
```

```bash
> pip list
Package           Version
----------------- -------
greenlet          2.0.1
inflect           6.0.2
pip               22.2.2
pydantic          1.10.2
PyMySQL           1.0.2
setuptools        65.4.1
sqlacodegen       2.3.0
SQLAlchemy        1.4.44
typing_extensions 4.4.0
```
Versions:
```bash
> sqlacodegen --version
2.3.0
> python --version
Python 3.10.8
```

**Comment by agronholm** [comment]
Please include repro instructions, starting from the creation of fresh virtualenv.

**Comment by jesperbruunhansen** [comment]
Hi @agronholm - Sorry, for not including it, but yes - I've done exactly that! 

First `python3.10 -m venv <my-venv>` then `pip install sqlacodegen`. After this, I get the error above when executing your CLI

**Comment by agronholm** [comment]
You need to install `pymsql` first.

**Comment by jesperbruunhansen** [comment]
Hi @agronholm - I've updated the issue with the _exact_ steps of how I get the error - just tested it now from a clean run

**Comment by agronholm** [comment]
And you're still getting `ModuleNotFoundError`? I'm not. Could you update the traceback too?

**Comment by jesperbruunhansen** [comment]
@agronholm, yes unfortunately - The traceback is identical to what its in the issue right now :(

**Comment by agronholm** [comment]
Then it's not running from the virtualenv, clearly. Try running `hash -r` and try again.

**Comment by agronholm** [comment]
When you run external commands, the shell looks them up via `PATH` and, on success, caches the command name and its path to avoid these costly checks on subsequent calls. `hash -r` clears that cache.
