### ISSUE TITLE
I'm getting this issue: 'Table' object has not attribute 'bind'. Haven't found solution so far.

### ISSUE THREAD

**Issue by GianmarcoSalvi** [agronholm/sqlacodegen#250]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/54672369/218248331-71fda75e-0e32-4734-9eda-f88143546f40.png">

**Comment by agronholm** [comment]
Which versions of sqlacodegen and sqlalchemy are you running?

**Comment by MrPranav101** [comment]
@GianmarcoSalvi 
@agronholm 
downgrade sqlalchemy to version lower than 2.0

pip install "sqlalchemy<2.0"

I think 2.0 breaks [sqlacodegen](https://github.com/agronholm/sqlacodegen) at least for postgres

**Comment by GianmarcoSalvi** [comment]
I tried downgrading at sqlalchemy=1.4.46, sqlacodegen=2.3.0
Now getting different issue
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/54672369/221297956-34c9d4b8-c07b-4a89-b90d-483b783f0e1b.png">

**Comment by MrPranav101** [comment]
@gian

Can you share the pip freeze for this environment?

**Comment by GianmarcoSalvi** [comment]
Yes, ofc. This is what i get doing pip freeze > requirements.txt
<img width="407" alt="image" src="https://user-images.githubusercontent.com/54672369/221348337-dd366113-d983-4b9f-a91e-67b16ce22f71.png">

**Comment by agronholm** [comment]
The combination of SQLAlchemy 1.4 and 3.0.0rc1 should work. Let me know if it doesn't. One problem with 2.0 and the `master` branch is that SQLModel does not work with SQLAlchemy 2.0. Otherwise I would up the requirement there.

**Comment by agronholm** [comment]
In the short term, I plan to limit the SQLAlchemy version to `<2.0`. Later I will add proper support for 2.0.

**Comment by agronholm** [comment]
I've restricted the SQLAlchemy version to < 2.0 for the time being.
