### ISSUE TITLE
sqlacodegen giving Unknown database on mysql+pymysql

### ISSUE THREAD

**Issue by AndyAndurkar** [agronholm/sqlacodegen#255]
I am getting the following error while using sqlcodegen with mysql
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'engine(mysql+pymysql://xxx:***@localhost:3306/mydb)'")

[SQL: SHOW FULL TABLES FROM `Engine(mysql+pymysql://xxxx:***@localhost:3306/mydb)`]

**Comment by agronholm** [comment]
Would you mind sharing some details on how you got that error? How did you invoke sqlacodegen, exactly? What version of sqlacodegen and sqlalchemy did you use?

**Comment by AndyAndurkar** [comment]
python --version
Python 3.7.9

sqlacodegen --version
2.3.0

Database: mysql

Driver: mysql+pymysql

sqlacodegen  "mysql+pymysql://XX:YY@localhost:3306/MYDB"

Thanks for your help. Does this help?

**Comment by agronholm** [comment]
But which version of SQLAlchemy? Could you try with v1.4?

**Comment by agronholm** [comment]
Also, try sqlacodegen v3.0.0rc1 with SQLAlchemy 1.4.
