### ISSUE TITLE
sqlacodegen does not document current support channels?

### ISSUE THREAD

**Issue by zzzeek** [agronholm/sqlacodegen#256]
hi !

We've had two unanswered sqlacodegen questions on the SQLAlchemy google group in two days.  There seems to be user help available here in the sqlacodegen github discussions..

can sqlacodegen clarify where its users should get support in its README?    Right now the README points to the sqlalchemy google group for support and I dont support sqlacodegen users myself; i will gladly direct those users here.

**Comment by agronholm** [comment]
Sure, I'll fix that.
