### ISSUE TITLE
codegen.py:390: SAWarning: Cannot correctly sort tables

### ISSUE THREAD

**Issue by ManPython** [agronholm/sqlacodegen#267]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

2.3.0.post1

### SQLAlchemy version

1.4.45

### RDBMS vendor

MySQL (or compatible)

### What happened?

```
codegen.py:390: SAWarning: Cannot correctly sort tables; there are unresolvable cycles between tables "items, items2", which is usually caused by mutually dependent foreign key constraints.  Foreign key constraints involving these tables will not be considered; this warning may raise an error in a future release.
```

### Database schema for reproducing the bug

It's well know problem:
https://stackoverflow.com/questions/64807850/sqlalchemy-multiple-one-to-one-and-one-to-many-relationships

**Comment by ManPython** [comment]
```
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.45
    Uninstalling SQLAlchemy-1.4.45:
      Successfully uninstalled SQLAlchemy-1.4.45
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sqlacodegen 2.3.0.post1 requires SQLAlchemy<2.0,>=0.9.0, but you have sqlalchemy 2.0.15 which is incompatible.
Successfully installed sqlalchemy-2.0.15
```

**Comment by agronholm** [comment]
Why are you reporting this as a bug?

**Comment by ManPython** [comment]
Coz "there are tcycles between tables", the FK - foregin key is something normal if multiplied relation exist
"Foreign key constraints involving these tables will not be considered" - FK must be considered.. eg. unique and normal index as both applied to the columns.

**Comment by agronholm** [comment]
So then you do have FK cycles between tables, and the warning is appropriate? The warning doesn't even come from sqlacodegen, but SQLAlchemy.
