### ISSUE TITLE
fix function name in codegen.py for python v3.11

### ISSUE THREAD

**Issue by MMF3775** [agronholm/sqlacodegen#274]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

2.3.0.post1

### SQLAlchemy version

1.4.49

### RDBMS vendor

PostgreSQL

### What happened?

in inspect.py in python 3.11 ArgSpec variable name changed to FullArgSpec and if we use this package in python 3.11 we got error **"from inspect import ArgSpec**
**ImportError: cannot import name 'ArgSpec' from 'inspect' (C:\Python311\Lib\inspect.py)"**

it will be fixed if you change "from inspect import ArgSpec" to "from inspect import FullArgSpec" in codegen.py

**Comment by agronholm** [comment]
Already fixed in master, and in the 3.0 release candidates.
