### ISSUE TITLE
Feature Request: Support for PostGIS

### ISSUE THREAD

**Issue by agronholm** [agronholm/sqlacodegen#29]
Originally reported by: **James Westover (Bitbucket: [westover](https://bitbucket.org/westover), GitHub: [westover](https://github.com/westover))**

----------------------------------------

Love the project. As a suggested feature would be to add support for PostGIS via the GeoAlchemy2 library. 

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/sqlacodegen/issue/29

**Comment by rajesh-kanakabandi** [comment]
any update on this issue?

**Comment by agronholm** [comment]
I haven't worked on this library for a good while now. I made the mistake of starting the 2.0 refactoring before I had committed enough time to do it. I plan to make a number of improvements in the next couple weeks and make a new release too.

**Comment by JonnoFTW** [comment]
This fix doesn't work for me, I'm using a `POLYGON` and `POINT` type in mysql, and I get this error running latest sqlacodegen and geoalchemy:
```
venv/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/reflection.py:181: SAWarning: Did not recognize type 'polygon' of column 'area'
  (type_, name))
venv/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/reflection.py:181: SAWarning: Did not recognize type 'point' of column 'location'
  (type_, name))
```

I assume at this point it gives those fields null type and I get this error later in the code generation:

```
venv/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2973, in visit_null
    "type on this Column?" % type_)
sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?
```

**Comment by agronholm** [comment]
What the commit fixed was PostGIS support. It doesn't do anything about the corresponding types on MySQL. If you can point out what needs to be imported first, then please create a new issue for that.
