### ISSUE TITLE
relationship's "secondary" parameter does not take schema into account

### ISSUE THREAD

**Issue by agronholm** [agronholm/sqlacodegen#30]
Originally reported by: **Victor Prosolin (Bitbucket: [exfizik](https://bitbucket.org/exfizik), GitHub: [exfizik](https://github.com/exfizik))**

----------------------------------------

I have a bunch of tables in the DB with a naming scheme like *TBL_CONF_SOMETHING* which are mapped to classes as *class TBLCONFSOMETHING*.

And then I have some "correlation tables" which only have foreign key fields. those are represented as *Tables*, e.g.
t_TBL_CONF_SOMETHINGELSECORR = Table(...)

These correlation tables are references in some *relationship* fields. E.g. 

```
#!python

class TBLCONFDATACOLUMNS(Base):
    __tablename__ = 'TBL_CONF_DATACOLUMNS'
    __table_args__ = {u'schema': 'dbo'}

    COLUMN_ID = Column(Numeric(6, 0), primary_key=True)
    COLUMN_NAME = Column(String(50, u'SQL_Latin1_General_CP1_CI_AS'), nullable=False)
    DESCRIPTION = Column(String(50, u'SQL_Latin1_General_CP1_CI_AS'), nullable=False)

    TBL_CONF_BUILDINGLEVELS = relationship(u'TBLCONFBUILDINGLEVELS', secondary='TBL_WEB_COLUMNBUILDINGLEVELCORR')
    TBL_SRC_SPECIESTYPE = relationship(u'TBLSRCSPECIESTYPE', secondary='TBL_CONF_SPECIESCOLUMNCORR')

t_TBL_WEB_COLUMNBUILDINGLEVELCORR = Table(
    'TBL_WEB_COLUMNBUILDINGLEVELCORR', metadata,
    Column('COLUMN_ID', ForeignKey(u'dbo.TBL_CONF_DATACOLUMNS.COLUMN_ID'), primary_key=True, nullable=False),
    Column('PROJECT_ID', Numeric(6, 0), primary_key=True, nullable=False),
    Column('LEVEL', Integer, primary_key=True, nullable=False),
    ForeignKeyConstraint(['PROJECT_ID', 'LEVEL'], [u'dbo.TBL_CONF_BUILDINGLEVELS.PROJECT_ID', u'dbo.TBL_CONF_BUILDINGLEVELS.LEVEL']),
    schema='dbo'
)
```
But then when I'm trying to query something, I get the following error:

InvalidRequestError: When initializing mapper Mapper|TBLCONFDATACOLUMNS|TBL_CONF_DATACOLUMNS, expression 'TBL_WEB_COLUMNBUILDINGLEVELCORR' failed to locate a name ("name 'TBL_WEB_COLUMNBUILDINGLEVELCORR' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ess_db_util.db_models.envision.dbo.TBLCONFDATACOLUMNS'> class after both dependent classes have been defined.

Looks like the only way to fix it is to remove those relationships pointing to non-existing classes. 

This looks like a bug. What do you think? Or maybe there is a way to map these correlation tables as *classes*, like all the other tables?

I'm using version 1.1.6, MS SQL Server 2012 and pymssql backend.

Please let me know if you need more information. 

Thank you.

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/sqlacodegen/issue/30

**Comment by daringer** [comment]
mmh, looks like this is coming up again:

```python
Traceback (most recent call last):
  File "D:\portable_python_64bit\python-2.7.10.amd64\Scripts\sqlacodegen-script.py", line 11, in <module>
    load_entry_point('sqlacodegen==1.1.6', 'console_scripts', 'sqlacodegen')()
  File "D:\portable_python_64bit\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\portable_python_64bit\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "D:\portable_python_64bit\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "D:\portable_python_64bit\python-2.7.10.amd64\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\portable_python_64bit\python-2.7.10.amd64\lib\site-packages\flask_sqlacodegen-1.1.6.1-py2.7.egg\sqlacodegen\main.py", line 11, in <module>

    from sqlacodegen.codegen import CodeGenerator
  File "D:\portable_python_64bit\python-2.7.10.amd64\lib\site-packages\flask_sqlacodegen-1.1.6.1-py2.7.egg\sqlacodegen\codegen.py", line 504
    constraints = [c for c in assocation_table.constraints if isinstance(c, ForeignKeyConstraint)]
              ^
SyntaxError: invalid syntax
```
sooo, debugged it a little, found that "assocation_table.schema" is simply None, for all items in metadata.tables... this happened using a mssql database using pyodbc...

will provide the quick fix as a pull-request in some minutes...

**Comment by daringer** [comment]
mmmh, funny that the github repository already has a fix for that, but via pip I got a version with this bug, but ok, so it is resolved anyways...

**Comment by agronholm** [comment]
This traceback seems to come from flask_sqlacodegen?
