### ISSUE TITLE
Syntax Error in 3.0.0rc3

### ISSUE THREAD

**Issue by devspacenine** [agronholm/sqlacodegen#305]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

3.0.0rc3

### SQLAlchemy version

2.0.23

### RDBMS vendor

PostgreSQL

### What happened?

There is a syntax error on [line 74](https://github.com/agronholm/sqlacodegen/blob/3.0.0rc3/src/sqlacodegen/cli.py#L74) of `src/sqlacodegen/cli.py`.

The `options` attribute of the `args` object is misspelled. `set(args.option.split(","))` should instead read `set(args.options.split(","))`

**Comment by agronholm** [comment]
This was fixed in #283. I need to make a new release.

**Comment by babinos87** [comment]
Hi, are you planning to make a new release or should we fork and fix this typo (or just install from git on the specific commit)?

**Comment by agronholm** [comment]
Apologies, I was sidetracked again by other projects. I've pushed v3.0.0rc4 now.
If you're interested in maintaining a fork, why not maintain this project directly? The position is open.

**Comment by babinos87** [comment]
I have no problem to perform admin tasks in the repo, but I am not familiar with it enough to actively develop on it.

I have never maintained an open project though so I am not sure if you want me to maintain this project.

**Comment by agronholm** [comment]
Alright, I just thought I'd ask.
