### ISSUE TITLE
No poetry package which supports SQLAlchemy 2.0

### ISSUE THREAD

**Issue by peteratdemtec** [agronholm/sqlacodegen#307]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

2.0.222.3.0.post1

### SQLAlchemy version

2.0.22

### RDBMS vendor

PostgreSQL

### What happened?

Running `poetry add sqlacodegen` with SQLAlchemy ^2.0.22 fails when installing sqlacodegen (2.3.0.post1): 

```
Because no versions of sqlacodegen match >2.3.0.post1,<3.0.0
 and sqlacodegen (2.3.0.post1) depends on SQLAlchemy (>=0.9.0,<2.0), sqlacodegen (>=2.3.0.post1,<3.0.0) requires SQLAlchemy (>=0.9.0,<2.0).
So, because launchpad depends on both sqlalchemy (^2.0.22) and sqlacodegen (^2.3.0.post1), version solving failed.
```

Submitting this as a bug because the README states that sqlacodegen supports SQLAlchemy 2, which it clearly does not--at least, not without manually installing versions marked as "pre-release," which is neither clear nor accurate according to any version of sqlacodegen available via standard Python package managers. 

Please revise the README to correctly indicate support for only supported versions of SQLAlchemy--and please release 2.0 support, as soon as you can! 

Thank you!

**Comment by agronholm** [comment]
What's the problem with installing a pre-release version? The [latest pre-release](https://pypi.org/project/sqlacodegen/3.0.0rc3/) does support SQLAlchemy 2.0. I'm working on getting this out the door, but it's taking a while. And I don't think the [PyPI page for the latest official release](https://pypi.org/project/sqlacodegen/) misrepresents thing. If you come to GitHub and see something in the README, and then install some other version than the latest, is that my fault?

**Comment by peteratdemtec** [comment]
I agree, the PyPI page for the latest official release is perfectly accurate! But I happened to find this page first, which indicates that the project, installable via `pip` (and presumably also poetry) supports 2.0, which it of course does not, which was rather disappointing for me. I'm sure other users have experienced or will experience this, even if they won't go so far as to file a bug report about it. 

If your intention is to show that this project is compatible with 2.0, maybe being more clear that ONLY the pre-release versions (which must be manually installed and are not available via `pip` or `poetry`) provide that compatibility would save you from wasting your time responding to bug reports.

Sorry to bother you, looking forward to 3.0!

**Comment by peteratdemtec** [comment]
I understand that's probably more trouble than it's worth for this kind of project. Please accept my apology and feel free to close this as resolved. Looking forward to 3.0

**Comment by agronholm** [comment]
Nah, it's understandable. As you can see from PyPI's release history, this project has been stuck in the "release candidate" stage for quite a long time – much longer than originally intended, as this hasn't been a priority for me and I maintain two dozen other projects at the same time. But now I'm back working on this again and I expect to cut the final release within the next few weeks.
