### ISSUE TITLE
sqlalchemy.exc.OperationalError

### ISSUE THREAD

**Issue by imsomdev** [agronholm/sqlacodegen#319]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

sqlacodegen==3.0.0b2

### SQLAlchemy version

SQLAlchemy==1.4.51

### RDBMS vendor

MSSQL

### What happened?

```
  File "src/pymssql/_pymssql.pyx", line 653, in pymssql._pymssql.connect
sqlalchemy.exc.OperationalError: (pymssql._pymssql.OperationalError) (18456, b"Login failed for user 'sa'.DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (localhost)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (localhost)\n")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
`sqlacodegen mssql+pymssql://sql_username:sql_password@server/database` giving above error but with postgres it's working fine.

**Comment by agronholm** [comment]
What do you expect me to do about this?

**Comment by imsomdev** [comment]
> What do you expect me to do about this?

I mean, why like this? Am I doing anything wrong?

**Comment by agronholm** [comment]
Well, from the error message if looks like the login failed, so wrong username/password combination. See if you can connect with bare sqlalchemy using the same connection URI.

**Comment by imsomdev** [comment]
> Well, from the error message if looks like the login failed, so wrong username/password combination. See if you can connect with bare sqlalchemy using the same connection URI.

No, the password and username combination is correct. But didn't check that with sqlalchemy. Will let you know tomorrow. Thanks.

**Comment by agronholm** [comment]
If your password contains certain special characters, they may need to be escaped.

**Comment by we684123** [comment]
To Future Readers,

If your password contains special characters, please use [Percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding) for encoding.

Alternatively, you can use the following Python code:
```python
import urllib.parse

# URL Encoding
original_string = "pa$ssw@ord"
encoded_string = urllib.parse.quote(original_string)
print(encoded_string) 

# URL Decoding
decoded_string = urllib.parse.unquote(encoded_string)
print(decoded_string) 
```
This method ensures that your password is correctly interpreted in URLs.

**Comment by agronholm** [comment]
Closing as obsolete, and probably a non-issue.
