### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by BabakAmini** [agronholm/sqlacodegen#325]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

2.3.0.post1

### SQLAlchemy version

2.0.30

### RDBMS vendor

PostgreSQL

### What happened?

Running sqlacodegen with or without arguments results in the error `ModuleNotFoundError: No module named 'pkg_resources'`. This occurs when using `pip install sqlacodegen`, which installs version 2.3.0.post1 from PyPi. If you install the most recent version from GitHub, there will not be any issues.

**Comment by scotscotmcc** [comment]
I just ran into this as well. on pypi.org for the project, you can go to 'release history' and it lists a number of newer versions as 'pre-release' (up to 3.0.0rc5 right now). you can install this from pypi with `pip install sqlacodegen==3.0.0rc5`

**Comment by agronholm** [comment]
Or with just `pip install --pre sqlacodegen`.

**Comment by agronholm** [comment]
Closing as a non-issue as it works with the latest pre-release.
