### ISSUE TITLE
Update cx_Oracle to python-oracledb

### ISSUE THREAD

**Issue by renatodamas** [agronholm/sqlacodegen#343]
### Things to check first

- [X] I have searched the existing issues and didn't find my feature already requested there

### Feature description

cx_Oracle no longer receive update.
The python-oracledb driver is a Python programming language extension module allowing Python programs to connect to [Oracle Database](https://www.oracle.com/database/). Python-oracledb is the new name for Oracle's popular cx_Oracle driver.

The installation process of  oracle_db don't require installation of adcional library on windows (microsoft c++ build tools) as cx_Oracle requires.

see more on: https://oracle.github.io/python-oracledb/ and https://levelup.gitconnected.com/what-is-the-difference-between-cx-oracle-and-python-oracledb-d2887336f75a

### Use case

To avoid security vulnerability of a non maintainable package.
see more on: https://oracle.github.io/python-oracledb/ and https://levelup.gitconnected.com/what-is-the-difference-between-cx-oracle-and-python-oracledb-d2887336f75a

**Comment by agronholm** [comment]
I'm sorry, where is sqlacodegen using `cx_Oracle`?

**Comment by renatodamas** [comment]
I've make a mistake. That issue is related with sqlalckemy and not sqlacodegen. And even with sqlalchemy, I thought the newer version has made this change.

My apologizes
