### ISSUE TITLE
How to generate from PostgreSQL without socket access?

### ISSUE THREAD

**Issue by gcavalcante8808** [agronholm/sqlacodegen#43]
Hello Folks,

I'm trying to generate models from a Database that is remote, but I'm receiving the following error:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

The command used to produce the error was:

sqlacodegen postgresql+psycopg2:///moodle:moodle@172.20.0.2/moodle

Thanks in Advance.

**Comment by agronholm** [comment]
You have on `/` too many in the URI.
