### ISSUE TITLE
Prefixing Sqlalchemy Core Tables with t_

### ISSUE THREAD

**Issue by pmart123** [agronholm/sqlacodegen#51]
I am not sure if this codebase is still being actively maintained, but I noticed what I believe is unexpected behavior when generating code for Sqlalchemy core models (noclass=True, inflict=True). Is there a reason why these class instances are generated with a "t_" i.e.:

```python
from sqlalchemy import Char, Column, MetaData, Table
from sqlacodegen.codegen import ModelTable

meta = MetaData()
table = Table('foobar', meta, Column('foo', CHAR(3), primary_key=True))
model_table = ModelTable(table)

>>> print(model_table).render())
>>> t_foobar = Table('foobar', metadata, Column('foo', String(3), primary_key=True))
```

**Comment by agronholm** [comment]
Yes, to prevent name conflicts. You can do a quick search&replace on the end result if you don't want this.
