### ISSUE TITLE
Invalid Identifier

### ISSUE THREAD

**Issue by harwee** [agronholm/sqlacodegen#52]
Invalid Identifier error after generating models for table with unicode chars in table name when importing the models.

    class 💞aussieBabe💞Index(Base):
                              ^
    SyntaxError: invalid character in identifier

* Python 3.6.1
* Anaconda 4.4.0 (64-bit)
* MSC v.1900 64 bit (AMD64)

**Comment by agronholm** [comment]
Already answered on [StackOverflow](https://stackoverflow.com/questions/46665030/syntaxerror-invalid-character-in-identifier-when-importing-models-generated-usi).

**Comment by harwee** [comment]
Yup, that was my question on StackOverflow, I raised the issue because code allows all Unicode chars to be present in the generated code, which is not accepted by python interpreter. I thought there should be a filter of some kind.

**Comment by agronholm** [comment]
There is no way the code generation can ever be perfect. Some sanity is expected from the developer side, like not putting strange characters in the names of tables or columns. It's just common sense.

**Comment by harwee** [comment]
Well, those charecters are perfectly accepted by postgresql, so I don't see any problem using those in my table names, it would make sense for me to use those names if necessary. I will work around this in someother way, thanks for you time.
