### ISSUE TITLE
My congratulations for this great tool

### ISSUE THREAD

**Issue by dcapeletti** [agronholm/sqlacodegen#63]
Simply sqlacodegen has saved my life. Having to write all the code in a database of 56 tables by hand can be a complex task and requires a lot of time and practice.
Simply thank for this fabulous tool, without a doubt it has been very useful.

Without more to say, if I find a problem, I will be reporting the same.
Congratulations for this great job! :-)

**Comment by dcapeletti** [comment]
SQLAlchemy should include a tool of this type or collaborate with this project.

**Comment by agronholm** [comment]
Thanks! If you know a specific location in SQLAlchemy's documentation where this should be mentioned, feel free to send a PR against it. I've already discussed this with its author, Mike Bayer.
