### ISSUE TITLE
Converts INTEGER from Oracle Database to NUMERIC - Results in Python FLOAT

### ISSUE THREAD

**Issue by jgfet** [agronholm/sqlacodegen#64]
Code was generated from SQLACODEGEN 1.1.6 on WIndows platform

From Toad:
JOBMST_TYPE	2		1	N	INTEGER		Frequency	3	0	1E-5				False

In generated Python code.
  jobmst_type = Column(Numeric(scale=0, asdecimal=False), nullable=False,
                         index=True)

http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.Numeric

This is not ideal. Was wondering why my data was coming out as 1.0 instead of 1 etc.

Would be better to use this if possible:
http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.Integer

**Comment by agronholm** [comment]
Would you mind trying against the latest master?

**Comment by agronholm** [comment]
Also, can you check what the reflection result was (before column type adaptation)?

**Comment by agronholm** [comment]
Over 2 years and no answer – closing as invalid.
