### ISSUE TITLE
Sqlacodegen breaks on primary key columns that aren't identity

### ISSUE THREAD

**Issue by koushikt** [agronholm/sqlacodegen#69]
When there is a primary key column that is not set as an identity column sqlacodegen ignores setting autoincrement=false explicitly. The default for autoincrement for a primary key column in sqlalchemy is true and this breaks inserts.

**Comment by agronholm** [comment]
How will sqlacodegen know that the pk isn't supposed to autoincrement?

**Comment by agronholm** [comment]
1.5 years without an answer – closing as invalid.
