### ISSUE TITLE
class models in different modules cannot share the same Base and metadata

### ISSUE THREAD

**Issue by nijm** [agronholm/sqlacodegen#73]
The declarative Base class is created in the generated output, which means the generated models can't share metadata with models defined in other modules (e.g., models generated by sqlacodegen from another schema).

Would you be open to adding an option for importing Base from another module?

Pull request here: #74

**Comment by agronholm** [comment]
I'm not open to this since the extra work for the user to handle this is fairly trivial and there's no way to get the splitting done just right for every user.
