### ISSUE TITLE
Add support for MySQL OpenGIS Spatial Data Types

### ISSUE THREAD

**Issue by osvalban** [agronholm/sqlacodegen#84]
I have a MySQL database with column type 'geometry'. The underlying data representation is an encoded hexadecimal blob, that can be decoded into 'Polygon' type by Geospatial libraries such as GDAL/OGR (https://www.osgeo.org/projects/gdal/).

running "sqlacodegen mysql://root:<password>@localhost/my_db" fails with the following exception:

"sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?"

Could you please add support for MySQL OpenGIS Spatial Data Types?:
https://dev.mysql.com/doc/refman/5.7/en/spatial-type-overview.html

I plan to build queries against this database with GeoAlchemy2, which does support Spatial Data Types.

If fixing this is non-trivial, can you add a feature to 'ignore' specific columns in a table and still generate SQLAlchemy  model code/declaratives for the rest of the columns that are supported?

Thanks,
Osvaldo

**Comment by osvalban** [comment]
sqlacodegen --version
2.0.1

**Comment by AtufaShireen** [comment]
did u fixed it? i have the same problem too

**Comment by agronholm** [comment]
What does sqlacodegen have to import to support these column types?

**Comment by agronholm** [comment]
I have not been able to find a Python library that supports these column types. Thus it is not possible to support them in sqlacodegen. What would you expect to see as the resulting column types anyway?
