### ISSUE TITLE
Columns named "text" break default string values in generated models

### ISSUE THREAD

**Issue by damon-myers** [agronholm/sqlacodegen#89]
Issue was found with:
* `sqlacodegen` version 2.0.1

Consider a table with the following schema:
```
CREATE TABLE table_with_text_field (
    id int NOT NULL AUTO_INCREMENT,
    text VARCHAR(255),
    another_field VARCHAR(255) DEFAULT "some text",
    PRIMARY KEY(id)
);
```

When using `sqlacodegen` to generate models for this table, we get:
```
...
class TableWithTextField(Base):
    __tablename__ = 'table_with_text_field'

    id = Column(INTEGER(11), primary_key=True)
    text = Column(String(255))
    another_field = Column(String(255), server_default=text("'a thing'"))
```

Notice that the `sqlalchemy.text` function gets shadowed, which results in a `TypeError: 'Column' object is not callable` whenever the model is used.

A naive solution would be to always call `sqlalchemy.text()` explicitly, rather than just `text()`.

I'd be glad to open a PR with a fix once we decide what the best fix would be.

**Comment by sh0rch** [comment]
from sqlalchemy.sql import text

**Comment by agronholm** [comment]
I think the best solution would be to alias the imports when a conflicting column name is detected.

**Comment by agronholm** [comment]
I'm working on this now. The plan is to generate variable/property names last, and if they conflict with previously assigned names in the current scope, add a suffix that avoids the conflict.
