### ISSUE TITLE
Is the generation done with NoLock

### ISSUE THREAD

**Issue by ing200086** [agronholm/sqlacodegen#94]
I tried to look this up, but maybe I am not providing the correct search terms. When the generation is occurring, are the inspections being done in a way which prevents locking on the database?

I am asking because my company has a large database which is used continuously. I obviously do not want to lock the database while I am inspecting it.

**Comment by agronholm** [comment]
That would depend on the RDBMS I guess? AFAIK at least PostgreSQL does not have any locking issues there. This is anyway something that is beyond the control of sqlacodegen, as it relies on SQLAlchemy's metadata reflection.
