### ISSUE TITLE
Class names missing an 's' at the end

### ISSUE THREAD

**Issue by dafvid** [agronholm/sqlacodegen#96]
Using statement `sqlacodegen --tables Business` generates the class 
```
class Busines(Entity):
    __tablename__ = 'Business'
```
Looking through the classnames it seems that every single table that ends with an 's' has lost it in the classname.

Fantastic tool anyhow. Great work.

**Comment by dafvid** [comment]
Better late than never. This fixed my issue. Thanks.

**Comment by ongopongo** [comment]
I noticed that in my project, too. The generated classes mapping to my `Analysis` and `Address` tables were named `Analysi` and `Addres`, respectively. 

Thanks, `amickael`. I wasn't aware of the `--noinflect` option. I'll try that next time!

For reference, here's the description of the `--noinflect` option from the script's usage string:

>don't try to convert tables names to singular form

https://github.com/agronholm/sqlacodegen/blob/master/sqlacodegen/main.py#L26-L27
