### ISSUE TITLE
Inflecting singular form specimen

### ISSUE THREAD

**Issue by MaximMoinat** [agronholm/sqlacodegen#98]
I have a table called `Specimen`. When generating classes, this is inflected to the (incorrectly derived) singular form `Speciman`. It is solved by adding the `--noinflect` flag, but it did confuse me at first. Maybe something to give as feed back to the inflection package?

Edit: opened as i[ssue in the jazzband/inflect repo](https://github.com/jazzband/inflect/issues/77)

**Comment by ongopongo** [comment]
>Maybe something to give as feed back to the inflection package?

I agree. One way may be to have the tool print a message to STDERR whenever it comes up with a class name that differs from the table name. For example:

```
Notice: Derived singular class name `Addres` from plural table name `Address`
Notice: Derived singular class name `Speciman` from plural table name `Specimen`
```

**Comment by agronholm** [comment]
As of ba08a71e2c85207ffedee52a6541e9b7df07f9d4, inflection is disabled by default. Hopefully this resolves the issue.
