### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by OpenHill** [agronholm/sqlacodegen#99]
Error:
(Apis) wang@wang:~/CodeFolder/Python/Apis$ flask-sqlacodegen mysql+pymysql://root:123@localhost/Apis>models.py --flask
Traceback (most recent call last):
  File "/home/wang/CodeFolder/venv/Apis/bin/flask-sqlacodegen", line 10, in <module>
    sys.exit(main())
  File "/home/wang/CodeFolder/venv/Apis/lib/python3.6/site-packages/sqlacodegen/main.py", line 59, in main
    args.flask, ignore_cols, args.noclasses)
  File "/home/wang/CodeFolder/venv/Apis/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 606, in __init__
    model = ModelClass(table, links[table.name], inflect_engine, not nojoined)
  File "/home/wang/CodeFolder/venv/Apis/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 335, in __init__
    relationship_ = ManyToManyRelationship(self.name, target_cls, association_table, inflect_engine)
  File "/home/wang/CodeFolder/venv/Apis/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 501, in __init__
    self.kwargs['secondary'] = repr(assocation_table.schema + '.' + assocation_table.name)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Test.Sql:**
`/*
 Navicat Premium Data Transfer

 Source Server         : localMysql
 Source Server Type    : MySQL
 Source Server Version : 50726
 Source Host           : localhost:3306
 Source Schema         : Apis

 Target Server Type    : MySQL
 Target Server Version : 50726
 File Encoding         : 65001

 Date: 03/07/2019 16:55:26
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for Button_Permission_Table
-- ----------------------------
DROP TABLE IF EXISTS `Button_Permission_Table`;
CREATE TABLE `Button_Permission_Table`  (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `PageId` int(11) NOT NULL,
  `CreateTime` datetime(0) NOT NULL ON UPDATE CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`Id`) USING BTREE,
  INDEX `PageId`(`PageId`) USING BTREE,
  INDEX `Id`(`Id`) USING BTREE,
  CONSTRAINT `Button_Permission_Table_ibfk_1` FOREIGN KEY (`PageId`) REFERENCES `Page_Permission_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for Menu_Permissio_Table
-- ----------------------------
DROP TABLE IF EXISTS `Menu_Permissio_Table`;
CREATE TABLE `Menu_Permissio_Table`  (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '菜单编号',
  `Name` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '菜单名称',
  `ToRouterAddress` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT '点击前往地址',
  `FatherId` int(11) NULL DEFAULT NULL COMMENT '父级编号',
  `CreateMan` int(11) NOT NULL COMMENT '创建者',
  `CreateTime` datetime(0) NOT NULL ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  PRIMARY KEY (`Id`) USING BTREE,
  INDEX `CreateMan`(`CreateMan`) USING BTREE,
  CONSTRAINT `Menu_Permissio_Table_ibfk_1` FOREIGN KEY (`CreateMan`) REFERENCES `UserInfo_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for Page_Permission_Table
-- ----------------------------
DROP TABLE IF EXISTS `Page_Permission_Table`;
CREATE TABLE `Page_Permission_Table`  (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `Name` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '页面名称',
  `ToRouterAddress` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '前往地址',
  `CreateMan` int(11) NOT NULL COMMENT '创建者',
  `CreateTime` datetime(0) NOT NULL ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  PRIMARY KEY (`Id`) USING BTREE,
  INDEX `CreateMan`(`CreateMan`) USING BTREE,
  CONSTRAINT `Page_Permission_Table_ibfk_1` FOREIGN KEY (`CreateMan`) REFERENCES `UserInfo_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for Roles_And_Button_Table
-- ----------------------------
DROP TABLE IF EXISTS `Roles_And_Button_Table`;
CREATE TABLE `Roles_And_Button_Table`  (
  `RoleId` int(11) NOT NULL,
  `BtnId` int(11) NOT NULL,
  INDEX `RoleId`(`RoleId`) USING BTREE,
  INDEX `BtnId`(`BtnId`) USING BTREE,
  CONSTRAINT `Roles_And_Button_Table_ibfk_1` FOREIGN KEY (`RoleId`) REFERENCES `Roles_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `Roles_And_Button_Table_ibfk_2` FOREIGN KEY (`BtnId`) REFERENCES `Button_Permission_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for Roles_And_Users_Table
-- ----------------------------
DROP TABLE IF EXISTS `Roles_And_Users_Table`;
CREATE TABLE `Roles_And_Users_Table`  (
  `RoleId` int(11) NOT NULL,
  `UserId` int(11) NOT NULL,
  INDEX `RoleId`(`RoleId`) USING BTREE,
  INDEX `UserId`(`UserId`) USING BTREE,
  CONSTRAINT `Roles_And_Users_Table_ibfk_1` FOREIGN KEY (`RoleId`) REFERENCES `Roles_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `Roles_And_Users_Table_ibfk_2` FOREIGN KEY (`UserId`) REFERENCES `UserInfo_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for Roles_Table
-- ----------------------------
DROP TABLE IF EXISTS `Roles_Table`;
CREATE TABLE `Roles_Table`  (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `Name` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT '角色名',
  `CreateMan` int(11) NOT NULL COMMENT '创建者',
  `CreateTime` datetime(0) NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`Id`) USING BTREE,
  CONSTRAINT `Roles_Table_ibfk_1` FOREIGN KEY (`Id`) REFERENCES `UserInfo_Table` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for UserInfo_Table
-- ----------------------------
DROP TABLE IF EXISTS `UserInfo_Table`;
CREATE TABLE `UserInfo_Table`  (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `Account` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '登录账号',
  `Pws` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密码',
  `Name` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名称',
  `Status` int(1) NOT NULL COMMENT '0 未激活 1 激活 2 封禁',
  `CreateTime` datetime(0) NOT NULL ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  PRIMARY KEY (`Id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10000 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;`

**Comment by OpenHill** [comment]
我的解决方案 (可能出错)

source file： codegen.py
line: 499
## 修改后
`class ManyToManyRelationship(Relationship):
    def __init__(self, source_cls, target_cls, assocation_table, inflect_engine):
        super(ManyToManyRelationship, self).__init__(source_cls, target_cls)
        

        # this
        self.kwargs['secondary'] = repr(assocation_table.schema
                                        if assocation_table.schema else "" + '.' + assocation_table.name)


        constraints = [c for c in assocation_table.constraints if isinstance(c, ForeignKeyConstraint)]
        constraints.sort(key=_get_constraint_sort_key)
        colname = _get_column_names(constraints[1])[0]
        tablename = constraints[1].elements[0].column.table.name
        self.preferred_name = tablename if not colname.endswith('_id') else colname[:-3] + 's'
        self.backref_name = inflect_engine.plural_noun(self.backref_name)

        # Handle self referential relationships
        if source_cls == target_cls:
            self.preferred_name = 'parents' if not colname.endswith('_id') else colname[:-3] + 's'
            pri_pairs = zip(_get_column_names(constraints[0]), constraints[0].elements)
            sec_pairs = zip(_get_column_names(constraints[1]), constraints[1].elements)
            pri_joins = ['{0}.{1} == {2}.c.{3}'.format(source_cls, elem.column.name, assocation_table.name, col)
                         for col, elem in pri_pairs]
            sec_joins = ['{0}.{1} == {2}.c.{3}'.format(target_cls, elem.column.name, assocation_table.name, col)
                         for col, elem in sec_pairs]
            self.kwargs['primaryjoin'] = (
                repr('and_({0})'.format(', '.join(pri_joins))) if len(pri_joins) > 1 else repr(pri_joins[0]))
            self.kwargs['secondaryjoin'] = (
                repr('and_({0})'.format(', '.join(sec_joins))) if len(sec_joins) > 1 else repr(sec_joins[0]))`

**Comment by agronholm** [comment]
Could you create a minimum viable example of this, preferably using sqlite? I'd like to understand how the `schema` attribute could be `None`.

**Comment by agronholm** [comment]
This should no longer be an issue in the 3.x series.
